FROM nginx

COPY ./nginx/default.conf /etc/nginx/conf.d/

CMD /bin/sh -c "envsubst < /usr/share/nginx/html/assets/js/env.template.js > /usr/share/nginx/html/assets/js/env.js && nginx -g 'daemon off;'"